### ISSUE TITLE
change ReCaptcha language

### ISSUE THREAD

**Issue by barakat-turki** [DanSnow/vue-recaptcha#107]
How can change the ReCaptcha language?

**Comment by DanSnow** [comment]
ReCAPTCHA language can configure by url parameter ([doc](https://developers.google.com/recaptcha/docs/display#config)).
Here's an example. [codepen](https://codepen.io/dododavid006/pen/bLprQM?editors=1010)
It just load the recaptcha after user selecting a language.

**Comment by barakat-turki** [comment]
Thanks, @DanSnow, but in this case should I remove the script and recreate it after every language changed, right?

**Comment by barakat-turki** [comment]
Thanks, @DanSnow

**Comment by DanSnow** [comment]
I think you should load recpatcha until you really need it.
Because it seem that loading recaptcha multiple time will break some function of rendered recaptcha.
Also recreating the script with new language parameter doesn't change recaptcha language.
It still use the initial language.
I don't think that dynamically changing language is supported.

**Comment by barakat-turki** [comment]
Yeah, for that reason I reloading the page when the language is changed, Thanks.

**Comment by FireflyStars** [comment]
there is no option to change language using your package?

**Comment by DanSnow** [comment]
@FireflyStars Currently, yes.  You need to configure with url parameter of recaptcha api

**Comment by DanSnow** [comment]
@FireflyStars It now support in v1.3.0
