### ISSUE TITLE
reCAPTCHA couldn't find user-provided function: vueRecaptchaApiLoaded

### ISSUE THREAD

**Issue by FreddyCrugger** [DanSnow/vue-recaptcha#247]
Hello,

I keep seeing this message in my production server console, any idea what does this means please?
`reCAPTCHA couldn't find user-provided function: vueRecaptchaApiLoaded`

Thank you

**Comment by DanSnow** [comment]
Its' because Google's recaptcha API is loaded before vue-recpatcha (or your app bundle that contains vue-recaptcha). Actually it won't effect anything. vue-recaptcha should still work properly. If not, please fire a issue.

Also this issue is already in [FAQ](https://github.com/DanSnow/vue-recaptcha#what-is-recaptcha-couldnt-find-user-provided-function-vuerecaptchaapiloaded)

**Comment by mangrove108** [comment]
I ve found this article about this issue, it helped me solve the thing.
[https://vueschool.io/articles/vuejs-tutorials/how-to-load-third-party-scripts-in-nuxt-js/](url)
