### ISSUE TITLE
vue-recaptcha causes a memory leak on route changes

### ISSUE THREAD

**Issue by jazoom** [DanSnow/vue-recaptcha#41]
I believe the offending reference is `window.___grecaptcha_cfg` since when I force it to be null before destroying the component I use vue-recaptcha in the problem disappears.

To reproduce just enter and exit the page where vue-recaptcha is in use.

**Comment by DanSnow** [comment]
Sorry, I'm afraid that I can't offer any help about this issue.
I believe that `window.___grecaptcha_cfg` is an internal object use by Google ReCAPTCHA.
Since it also can be found in a page like [this](https://patrickhlauke.github.io/recaptcha/), which  is using a vanilla reCAPTCHA.
I can just force `window.__grecaptcha_cfg` to be null when component unmount.
But in my opinion, I shouldn't place any code in a library, which possibly can break reCAPTCHA's functionality someday.
If your app is facing a seriously memory leak problem, please just force `window.___grecaptcha_cfg` to be null as you mentioned.

If you have any idea, please let me know.

**Comment by jazoom** [comment]
It seems we're not the only ones: http://stackoverflow.com/questions/42332165/how-to-remove-a-programatically-loaded-recaptcha-v2

I guess it's just poor design on Google's part.

**Comment by Scaenicus** [comment]
Could this be a solution?
https://vuejs.org/v2/guide/components.html#keep-alive
