### ISSUE TITLE
Recaptcha won't show after success several times 

### ISSUE THREAD

**Issue by randichilyon** [DanSnow/vue-recaptcha#528]
Hi,

I'm developing a feature which uses vue-recaptcha. But after several times, the captcha won't show anymore. Is there any methods to always show the captcha? thank you

**Comment by DanSnow** [comment]
What do you mean for showing the captcha? If you cannot see the checkbox, please check your console in devtool and provide the message.

If you didn't see the challenge, that is because Google think the user is a human. There doesn't have a way to force it to show the challenge. 

Also if the response from reCAPTCHA doesn't expired and you want to ask it to verify the user again, you'll need to call the `reset` to reset the reCAPTCHA.
